### PR TITLE
fix: resolve crash in `TransformModuleFilesToModel` if regular schema file passed instead

### PR DESCRIPTION
**Pull request by fsedano**
## Description

The change checks the metadata for the module, if it's null it returns the proper error.

## References

Fixes https://github.com/openfga/language/issues/384

## Review Checklist
- [X] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [X] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [X] The correct base branch is being used, if not `main`
- [X] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by fsedano** [comment]
@elbuo8 - Hi, would it be possible to have a review on this? It's impacting our production code and I rather not deploy a patched version, so would love having this fixed upstream. Thanks!

**Comment by rhamzeh** [comment]
@fsedano - do you require an error? What do you think about returning a transformation with the module name empty?

**Comment by fsedano** [comment]
@rhamzeh In general I'd prefer to have an error, since this is most probably a input error. If the user wants to accept both it could catch the error and use the regular API for that. If we just hide the error it will go unnoticed and it might have unexpected side effects.

The way this was caught in prod is because somebody by mistake commited the wrong file as a module. I rather error out to point the user about the mistake.

**Comment by rhamzeh** [comment]
> @rhamzeh In general I'd prefer to have an error, since this is most probably a input error. If the user wants to accept both it could catch the error and use the regular API for that. If we just hide the error it will go unnoticed and it might have unexpected side effects.
> 
> The way this was caught in prod is because somebody by mistake commited the wrong file as a module. I rather error out to point the user about the mistake.
> 

Thanks for elaborating, will merge this to unblock you, and in the future we'll add options to allow this use-case.

The one I currently forsee is allowing folks to run and test and transform their module without worrying about the module file and then a separate platform process does the combining - but as that is not a current use-case, it shouldn't be a blocker.

Will add an issue for us to port this change to JS and Java to maintain consistency.

May I ask how are you consuming this? Is it by calling it directly or through the CLI? (to see if we need to spin up a new CLI release that contains this fix to unblock you)

**Review by rhamzeh — APPROVED** [review]

**Comment by fsedano** [comment]
Thanks @rhamzeh  - Just fixed also the JS one, thanks for letting me know.
We are not using CLI, but the Go SDK, so no CLI hotfix is needed.

Thanks again!

**Review by rhamzeh — APPROVED** [review]

**Comment by fsedano** [comment]
Thanks @rhamzeh  - Is there anything else I have to do to have this merged or will it happen automagically? Thanks,

**Comment by rhamzeh** [comment]
Was waiting for all the tests to pass, just added it to the queue.

Thanks for the fix!

**Pull request merged**
